include: package:lint/analysis_options.yaml

linter:
  rules:
    always_specify_types: true
    missing_whitespace_between_adjacent_strings: false
    overridden_fields: false
    require_trailing_commas: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
