name: flutter_config_example
description: Demonstrates how to use the flutter_config plugin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_config:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter:
  uses-material-design: true
