include: package:lint/analysis_options_package.yaml

linter:
  rules:
    always_specify_types: true
    missing_whitespace_between_adjacent_strings: false
    overridden_fields: false
    require_trailing_commas: true

analyzer:
  exclude:
    - 'lib/generated_plugin_registrant.dart'
  errors:
    missing_required_param: error
    missing_return: error
